drops:
    worlds:
        world:
            mobs:
                CAVE_SPIDER:
                    chance: .00025
                    amount:
                        min: 1
                        max: 1
                CREEPER:
                    chance: .002
                    amount:
                        min: 1
                        max: 1
                ENDERMAN:
                    chance: .005
                    amount:
                        min: 1
                        max: 1
                ENDERMITE:
                    chance: .002
                    amount:
                        min: 1
                        max: 1
                GIANT:
                    chance: 0.5
                    amount:
                        min: 1
                        max: 2
                GUARDIAN:
                   chance: .005
                   amount:
                        min: 1
                        max: 2
                SILVERFISH:
                    chance: .0002
                    amount:
                        min: 1
                        max: 1
                SKELETON:
                    chance: .0005
                    amount:
                        min: 1
                        max: 1
                SLIME:
                    chance: .002
                    amount:
                        min: 1
                        max: 1
                SPIDER:
                    chance: .0005
                    amount:
                        min: 1
                        max: 1
                WITCH:
                    chance: .003
                    amount:
                        min: 1
                        max: 1
                WITHER:
                    chance: 0.05
                    amount:
                        min: 1
                        max: 3
                ZOMBIE:
                    chance: .0005
                    amount:
                        min: 1
                        max: 1
            blocks:
                DIAMOND_ORE:
                    chance: .0075
                    amount:
                        min: 1
                        max: 2
                EMERALD_ORE:
                    chance: .01
                    amount:
                        min: 1
                        max: 2
                LAPIS_ORE:
                    chance: .0025
                    amount:
                        min: 1
                        max: 1
                GOLD_ORE:
                    chance: .0005
                    amount:
                        min: 1
                        max: 1
                IRON_ORE:
                    chance: .00025
                    amount:
                        min: 1
                        max: 1
                COAL_ORE:
                    chance: .000125
                    amount:
                        min: 1
                        max: 1
                REDSTONE_ORE:
                    chance: .000125
                    amount:
                        min: 1
                        max: 1
                STONE:
                    chance: .000075
                    amount:
                        min: 1
                        max: 1
                OBSIDIAN:
                    chance: .00075
                    amount:
                        min: 1
                        max: 1
    world_nether:
        mobs:
            BLAZE:        
                chance: .001
                amount:
                    min: 1
                    max: 1
            GHAST:
                chance: .01
                amount:
                    min: 1
                    max: 2
            MAGMA_CUBE:
               chance: .002
               amount:
                   min: 1
                   max: 1
            PIG_ZOMBIE:
                chance: .003
                amount:
                    min: 1
                    max: 1
            SKELETON:
                chance: .0005
                amount:
                    min: 1
                    max: 1
    world_the_end:
        mobs:
           ENDER_DRAGON:
                chance: 0.5
                amount:
                    min: 1
                    max: 3
           ENDERMAN:
                chance: .005
                amount:
                    min: 1
                    max: 1
           ENDERMITE:
                chance: .002
                amount:
                   min: 1
                   max: 1
        
upgrades:
    tiers:
        1:
            lore:
            - "Storm I"
            breakChance: 0.0
            failChance: 0.0
            broadcast: false
            lightning: true
            glow: true
            amount: 1
        2:
            lore:
            - "Storm II"
            breakChance: 0.0
            failChance: 0.1
            broadcast: false
            lightning: true
            glow: true
            amount: 1
        3:
            lore:
            - "Storm III"
            breakChance: 0.1
            failChance: 0.1
            broadcast: true
            lightning: true
            glow: true
            amount: 1
        4:
            lore:
            - "Storm IV"
            breakChance: 0.1
            failChance: 0.2
            broadcast: true
            lightning: true
            glow: true
            amount: 1
        5:
            lore:
            - "Storm V"
            breakChance: 0.2
            failChance: 0.3
            broadcast: true
            lightning: true
            glow: true
            amount: 1
    location:
        x: -71
        y: 74
        z: -243
        world: world

item:
    name: "&3Storm Shard"
    lore:
    - "&7The shard glows of an &3ancient &7power"
    - "&7Use &3/sts help &7for info"
    material: PRISMARINE_SHARD
    glow: true

stats:
    items:
        helmets:
            materials:
            - CHAINMAIL_HELMET
            - DIAMOND_HELMET
            - GOLD_HELMET
            - IRON_HELMET
            - LEATHER_HELMET
            damageReduction:
                1: .01
                2: .02
                3: .03
                4: .04
                5: .05
        chestplates:
            materials:
            - CHAINMAIL_CHESTPLATE
            - DIAMOND_CHESTPLATE
            - GOLD_CHESTPLATE
            - IRON_CHESTPLATE
            - LEATHER_CHESTPLATE
            damageReduction:
                1: .03
                2: .04
                3: .05
                4: .06
                5: .07
        leggings:
            materials:
            - CHAINMAIL_LEGGINGS
            - DIAMOND_LEGGINGS
            - GOLD_LEGGINGS
            - IRON_LEGGINGS
            - LEATHER_LEGGINGS
            damageReduction:
                1: .02
                2: .03
                3: .04
                4: .05
                5: .06
        boots:
            materials:
            - CHAINMAIL_BOOTS
            - DIAMOND_BOOTS
            - GOLD_BOOTS
            - IRON_BOOTS
            - LEATHER_BOOTS
            damageReduction:
                1: .01
                2: .02
                3: .03
                4: .04
                5: .05
        swords:
            materials:
            - DIAMOND_SWORD
            - GOLD_SWORD
            - IRON_SWORD
            - STONE_SWORD
            - WOOD_SWORD
            damageIncrease:
                1: .10
                2: .20
                3: .30
                4: .40
                5: .50
        bow:
            materials:
            - BOW
            damageIncrease:
                1: .10
                2: .20
                3: .30
                4: .40
                5: .50
        pickaxes:
            materials:
            - DIAMOND_PICKAXE
            - GOLD_PICKAXE
            - IRON_PICKAXE
            - STONE_PICKAXE
            - WOOD_PICKAXE
            damageIncrease:
                1: .10
                2: .20
                3: .30
                4: .40
                5: .50
        axes:
            materials:
            - DIAMOND_AXE
            - GOLD_AXE
            - IRON_AXE
            - STONE_AXE
            - WOOD_AXE
            damageIncrease:
                1: .10
                2: .20
                3: .30
                4: .40
                5: .50
        shovels:
            materials:
            - DIAMOND_SPADE
            - GOLD_SPADE
            - IRON_SPADE
            - STONE_SPADE
            - WOOD_SPADE
            damageIncrease:
                1: .10
                2: .20
                3: .30
                4: .40
                5: .50
        hoes:
            materials:
            - DIAMOND_HOE
            - GOLD_HOE
            - IRON_HOE
            - STONE_HOE
            - WOOD_HOE
            damageIncrease:
                1: .10
                2: .20
                3: .30
                4: .40
                5: .50