name: stShards
version: 2.0.5-SNAPSHOT
description: A unique end-game survival mechanic
author: tmad40blue
website: http://tmad40.blue/

main: blue.tmad40.stShards.Main

commands:
    sts:
        description: Base command
        aliases: [stormshards]
        
permissions:
    stShards.*:
        description: Gives access to all plugin functions
        children:
            stShards.reload: true
            stShards.help: true
            stShards.use: true
            stShards.find: true
    stShards.reload:
        description: Gives access to /sts reload
        default: op
    stShards.help:
        description: Gives access to /sts reload
        default: true
    stShards.use:
        description: Gives access to /sts reload
        default: true
    stShards.find:
        description: Gives access to /sts reload
        default: true